version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
  redis:
    image: redis/redis-stack-server:7.2.0-M01
    ports:
      - 6379:6379
    networks:
      - backend
  backend:
    build: ./
    command: npm run dev:server
    ports:
      - 3333:3333
    volumes:
      - ./:/api
    depends_on:
      - redis
      - postgres
    networks:
      - backend

volumes:
  data: {}
  db: {}

networks:
  backend:
    name: api_node_network
