version: '3.8'

services:
  db:
    build: ./sql
    restart: always
    env_file:
      - '.env'
    ports:
      - 3306:3306
    healthcheck:
      test: 'mysql -u root -p ${MYSQL_ROOT_PASSWORD} -e "SHOW DATABASES;"'
      interval: 10s
      timeout: 60s
      retries: 3
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend
  redis:
    image: redis/redis-stack-server:7.2.0-M01
    ports:
      - 6379:6379
    networks:
      - backend
  backend:
    build: ./
    command: npm run dev:server
    ports:
      - 3333:3333
    volumes:
      - ./:/api
    depends_on:
      - db
      - redis
    networks:
      - backend

volumes:
  data: {}

networks:
  backend:
    name: api_node_network
