export { CreateGameDTO } from './CreateGameDTO'
export { CreateGenreDTO } from './CreateGenreDTO'
export { CreatePlatformDTO } from './CreatePlatformDTO'
export { DeleteGameDTO } from './DeleteGameDTO'
export { DeleteGenreDTO } from './DeleteGenreDTO'
export { DeletePlatformDTO } from './DeletePlatformDTO'
export { type GameResponseDTO } from './GameResponseDTO'
export { GetGameDTO } from './GetGameDTO'
export type { ResponseDTO } from './ResponseDTO'
export { UpdateGameDTO } from './UpdateGameDTO'
