export { AgeRatingRepository } from './AgeRatingRepository'
export { GameRepository } from './GameRepository'
export { GenreRepository } from './GenreRepository'
export { PlatformRepository } from './PlatformRepository'
export { ReviewerRepository } from './ReviewerRepository'
